<script>

  // Our imports.
  import {scale, slide, fade} from 'svelte/transition';
  import Header from './components/Header.svelte';
  import Footer from './components/Footer.svelte';
  import Register from './components/Register.svelte';
  import Login from './components/Login.svelte';
  import Profile from './components/Profile.svelte';
  
  // This will be used for tracking user session locally.
  const createSession = () => {
    return {
      api: "http://localhost:3000",
      username: "",
      loggedIn: false,
      admin: false,
      page: "Login",
      pages: ["Home", "Login", "Register", "About"]
    };
  };

  // For saving the session to local storage.
  const saveSession = () => {

    if (Storage){
      localStorage.setItem("exa", JSON.stringify(session));
      return true;
    }
    return false;
  };

  // For loading session from local storage.
  const loadSession = () => {
    
    let newSession = createSession();
    if (!Storage)
      return newSession;
    let savedSession = localStorage.getItem("exa");
    return (savedSession ? JSON.parse(savedSession) : newSession);
  };

  // Handles 'updateSession' event used by child components to update the session.
  const updateSession = (e) => {
    
    session = e.detail;
    saveSession();
  };

  // Initialize the session.
  let session = loadSession();
  if (session.loggedIn === true) // Change default page to homepage if user is already logged in.
    session.page = "Home";

  // Handles page switch event generated by child components.
  const switchPage = (e) => {
    
    let page = e.detail;
    if (page === "Logout")
      page = "Login";
    session.pages = ["Home", "Login", "Register", "About"];
    if (page === "Login" || page === "Register")
      session = createSession(); // Destroy the current session
    session.page = page;
    if (session.loggedIn === true){
      session.pages[1] = "Profile";
      session.pages[2] = "Logout";
      session.pages = session.pages;
    }
    saveSession();
  };

</script>

<main class="main-page mx-auto">
  <Header {session} on:switchPage={switchPage}/>
  <div class="main-content px-5">
    {#if (session.page === "Home")}
      <div in:fade={{duration: 200}}>        
        <h3>Courses</h3>
      </div>
    {:else if (session.page === "Register")}
      <div in:fade={{duration: 200}}>
        <Register {session} on:switchPage={switchPage}/>
      </div>
    {:else if (session.page === "Login" || session.page === "Logout")}
      <div in:fade={{duration: 200}}>
        <Login {session} on:switchPage={switchPage} on:updateSession={updateSession}/>
      </div>
    {:else if (session.page === "Profile")}
      <div in:fade={{duration: 200}}>
        <Profile {session} />
      </div>
    {:else}
      <div>
        <h3>Invalid page: {session.page}</h3>
      </div>
    {/if}
  </div>
  <Footer />
</main>