<script>
  
  /**
   * @file The primary component. Displays the header, page contents, and the footer.
   * @author Umar Abdul (https://github.com/4g3nt47)
   */

  import {scale, slide, fade} from 'svelte/transition';
  import Header from './components/Header.svelte';
  import Footer from './components/Footer.svelte';
  import Register from './components/Register.svelte';
  import Login from './components/Login.svelte';
  import Profile from './components/Profile.svelte';
  import Admin from './components/admin/Admin.svelte';
  import CourseList from './components/course/CourseList.svelte';
  
  /**
   * Creates a session object that's used for client-side logic.
   * @return {object} The session object.
   */
  const createSession = () => {
    return {
      api: "http://localhost:3000",
      username: "",
      loggedIn: false,
      admin: false,
      pages: ["Login", "Register", "About"],
      page: "Login",
      subPage: "",
      cache: {}
    };
  };

  /**
   * Saves the session object to local storage.
   * @return {boolean} true on success.
   */
  const saveSession = () => {

    if (Storage){
      localStorage.setItem("exa", JSON.stringify(session));
      return true;
    }
    return false;
  };

  /**
   * Loads session from local storage, or create a new one if none found.
   * @return {object} The session object.
   */
  const loadSession = () => {
    
    let newSession = createSession();
    if (!Storage)
      return newSession;
    let savedSession = localStorage.getItem("exa");
    return (savedSession ? JSON.parse(savedSession) : newSession);
  };

  /**
   * Handles 'updateSession' event used by child components to update the session.
   * @param {obect} e - The event object.
   */
  const updateSession = (e) => {
    session = e.detail;
    saveSession();
  };

  /**
   * Handles page switch event generated by child components.
   * @param {object} e - The event object.
   */
  const switchPage = (e) => {
    
    let page = e.detail;
    if (page === "Logout")
      page = "Login";
    if (page === "Login" || page === "Register") // Pages that require session reset.
      session = createSession(); // Destroy the current session
    session.page = page;
    if (session.loggedIn === true){ // Change nav for logged in users.
      if (session.pages[0] !== "Home")
        session.pages = ["Home", ...session.pages];
      session.pages[1] = "Profile";
      session.pages[2] = "About";
      session.pages[3] = "Logout";
      if (session.admin){ // Display administrative navs
        session.pages[2] = "Admin";
        session.pages[3] = "About";
        session.pages[4] = "Logout";
      }
      session.pages = session.pages;
    }
    saveSession();
  };
  
  // Initialize the session.
  let session = loadSession();

</script>

<main class="main-page mx-auto">
  <!-- The header -->
  <Header {session} on:switchPage={switchPage}/>
  <!-- The body/content -->
  <div class="main-content px-5">
    {#if (session.page === "Home")}
      <div in:fade={{duration: 200}}>        
        <CourseList {session} on:switchPage={switchPage}/>
      </div>
    {:else if (session.page === "Register")}
      <div in:fade={{duration: 200}}>
        <Register {session} on:switchPage={switchPage}/>
      </div>
    {:else if (session.page === "Login" || session.page === "Logout")}
      <div in:fade={{duration: 200}}>
        <Login {session} on:switchPage={switchPage} on:updateSession={updateSession}/>
      </div>
    {:else if (session.page === "Profile")}
      <div in:fade={{duration: 200}}>
        <Profile {session} />
      </div>
    {:else if (session.page === "Admin" && session.admin === true)}
      <div in:fade={{duration: 200}}>
        <Admin {session} on:updateSession={updateSession}/>
      </div>
    {:else}
      <div>
        <h3>Invalid page: {session.page}</h3>
      </div>
    {/if}
  </div>
  <!-- The footer -->
  <Footer />
</main>
